- Dockerfile
- README.md
Generated repo content using SDCLI, and added initial project overview.
> add initial README content

- Dockerfile
dep ensure was not being run in the docker build
> add dep step to dockerfile

- .golangci.yaml
- Dockerfile
- Gopkg.lock
- pkg/storage/config.go
- pkg/storage/db.go
- pkg/storage/db_test.go
- scripts/2_create.sql
- tests/storage_test.go
Add automated running of the table create scripts to bootstrap the system.
> Secd 449/db scripts in service

- api.yaml
Forgot to replace this in the API.yaml in the initial pass.
> Secd 481/add arn

- pkg/storage/db_test.go
The master build was [failing](https://travis-ci.com/asecurityteam/asset-inventory-api/builds/110758200) due to a bad merge or rebase. What was odd was that the feature branch was [green](https://travis-ci.com/asecurityteam/asset-inventory-api/builds/110540311) prior to merging.
> fix bad merge

- pkg/storage/db_test.go
It looks like the sdcli update got sandwiched between the time at which the branch build ran and the time I merged. The branch build had no linter issues, but once merged into master, the updates caught some existing linter errors.
> fix linter issues

- main.go
- pkg/storage/db.go
- tests/storage_test.go
* Run full integration test suit with every supported schema version starting with 1 (legacy)
* Fix typo in select query to make the test pass
> Integration tests with all known schema versions

- db-migrations/000005_adding_owners.down.sql
Step down needs a `cascade` in order to delete the dependent objects
> adding cascade statement

- tests/test-data/data.sql
Task from PR in asset-inventory-splunk https://bitbucket.org/asecurityteam/asset-inventory-splunk/pull-requests/28#comment-165035975
> add local ip to help ai splunk testing

- db-migrations/000009_adding_aws_resource_relationship.down.sql
- db-migrations/000009_adding_aws_resource_relationship.up.sql
Adding aws_resource_relationship table as per [SID-510](https://asecurityteam.atlassian.net/browse/SID-510)
> Adding aws_resource_relationship table

- db-migrations/000011_adding_functions.down.sql
- db-migrations/000011_adding_functions.up.sql
This pull request has changes in database to perform database migration.
> Creating functions to leverage postgres performance

- pkg/storage/db.go
- pkg/storage/db_test.go
- tests/test-data/data.sql
Reverts asecurityteam/asset-inventory-api#74
The pull request is reverted to merge API changes.
> Revert "Revert "Creating functions to leverage postgres performance""

- pkg/storage/db.go
I made the mistake in my previous PR of not properly testing the ARNID lookup. I needed to use pointers properly for that one as well. This time I tested the ip, hostname (these use the same method), and arnid lookups locally.
> Fix error with ARNID lookup

- Makefile
- integration.Dockerfile
- pkg/storage/db.go
I thought I had tested all possible null variations but it seems I missed one. This would be great to get through today so that on-call doesn't get any more alerts on this.
I'd like to go back and clean this code up at some point, but for now this will do.
> Fix null pointer error

- api.yaml
Adding timeouts to endpoints we have already added in the other bitbucket repository. See reviewers note below.
> adding timeouts to github as well

- .travis.yml
Follow-up to https://github.com/asecurityteam/asset-inventory-api/pull/90/files
> Bring integration tests from master back

- api.yaml
- integration/tests/cloudchanges_test.go
Basic validation for IP addresses via openapi
Visual for regexp:
> Add ip address validation, uncomment/improve tests

- api.yaml
- integration/tests/cloudchanges_test.go
- integration/tests/main_test.go
Re-uses the validator @akhalina wrote for other endpoints and adds tests.
> Add validation for Account ID and re-enable/add integration tests

- .travis.yml
Let's see if both branch and master pass...
> Switch master branch integration test back on

- integration/tests/post_accountowners_test.go
- integration/tests/sample_data_test.go
- pkg/handlers/v1/insert_account_owner.go
Adding integration tests for: /v1/account/owner POST endpoint.
> add integration tests for POSTing accountOwner
