asecurityteam/asset-inventory-api

- pkg/domain/cloud.go
- pkg/handlers/v1/cloud_fetch.go
- pkg/handlers/v1/cloud_fetch_test.go
- pkg/handlers/v1/cloud_insert.go
- pkg/handlers/v1/cloud_insert_test.go
- pkg/storage/db.go
- pkg/storage/db_test.go
- tests/storage_test.go
We no longer rely on the AWS resourceID as the unique identifier. We now use ARN which has the resource ID as well as additional identifying information
> remove resourceID

- api.yaml
- main.go
- pkg/domain/storage.go
- pkg/handlers/v1/get_partitions.go
- pkg/handlers/v1/get_partitions_test.go
- pkg/handlers/v1/mock_storage_test.go
- pkg/storage/db.go
- pkg/storage/db_test.go
- tests/storage_test.go
Currently, there is a mechanism by which we can create partitions in out PG database. For operational purposes, in testing and operating this feature, it would be useful to be able to view all current partitions in the DB.
This PR creates a new handler in the OSS project to fetch new partitions and an api.yaml entry which registers the new handler.
> add get handler for partitions

- api.yaml
- pkg/domain/storage.go
- pkg/handlers/v1/create_partition.go
- pkg/handlers/v1/create_partition_test.go
- pkg/handlers/v1/mock_storage_test.go
- pkg/storage/db.go
- pkg/storage/db_test.go
- tests/storage_test.go
Currently, the database partitions are hardcoded to 3 months. This PR makes a couple of adjustments:
- Change the default partition from 3 months to 90 days
- allows callers to specify a custom partition duration in # of days
> pass partition duration as a parameter

- api.yaml
- main.go
- pkg/domain/storage.go
- pkg/handlers/v1/delete_partitions.go
- pkg/handlers/v1/delete_partitions_test.go
- pkg/handlers/v1/mock_storage_test.go
- pkg/storage/config.go
- pkg/storage/config_test.go
- pkg/storage/db.go
- pkg/storage/db_test.go
- tests/storage_test.go
We have provided a way to create partitions. This will eventually result in the number of partitions growing at an unbounded rate. To address this, this PR adds a DELETE endpoint which will delete all partitions older than the specified number of days.
This PR does not include a mechanism to export data or archive data. If needed, that work will come later. Today this can be done by other (less elegant) ways such as restoring a database backup.
> add delete partitions function

- pkg/storage/config.go
- pkg/storage/db.go
- pkg/storage/db_test.go
- pkg/storage/read_config.go
Prevent replica DB connection initialization from attempting to create database and manage schema.
This is the final pass re: read replica support. The Docker image with changes from this branch is functional and correctly directs reads to replica.
NB - the schema management logic is going to change once we have tooling in place.
> Switch db reads to replica

- main.go
It has way better performance on main compared to replica. Our current check fails (times out) when this is run on replica as the call relies on bunch of `select count (*) from table` (one per partition). Long term plan is to get rid of/change the way we partition.
> Switch partition count operation to main

- pkg/storage/db.go
- scripts/3_create_v2.sql
The proposed new schema (with manual migration and performance testing so far, automation for both is to be done in scope of different PRs) was tested for performance comparison with existing one using the queries in this PR and production-like data. 
The storage was populated (for both cases) with ~10 mln resources and ~45 mln allocation/de-allocation events.
The query execution time for look-ups  (both hits and misses) using new schema did not exceed 100ms, which brings us well within reasonable execution time per request.
Caveats:
* not ALL the queries using old schema resulted in multi-second look-ups, but some  took 5+ seconds to complete with the data set I used. 
* the new schema was specifically compared against worst performing cases for current schema, and is more predictable …
> Normalized schema

- pkg/storage/db.go
- pkg/storage/db_test.go
~~NB, this will be updated to cover the new code path with tests properly, but otherwise looks complete. Considering that's a lot of SQL to review, throwing it in early.~~ Tests are there.
Based on the current schema version, after the existing code wrote the event to the existing schema, if the migration to add new tables was complete, the storeV2() is invoked to perform additional write to new schema.
The db inserts are written with possibility of out-of-band and out-of-order events, for example release event arriving before assign (e.g. dual writes and subsequent back-fill) in mind.
Special timestamp value is used to express 'unknown assignment date' to allow for catch-up update to record an assignment after the release event was already recorded.
Public IPs assignments always arrive …
> Dual-write events to new and old schema based on present schema version

- go.mod
- pkg/storage/db.go
- pkg/storage/db_test.go
"Find by Public IP" and "Find by Private IP" are combined into one pull request because the code change affects both. Summary of pull request:
- Add hostname as one of the return values in _resourceByPublicIPQuery_ query
- FetchByIP() function modified to work with old and new schema
- Add runFetchByIPQuery() to run queries, which are _resourceByPublicIPQuery_ and _resourceByPrivateIPQuery_ on new schema when called
- Add test cases
> Update fetch assets by private and public IP to match M1 schema

- pkg/storage/db.go
- pkg/storage/db_test.go
Adding reads for hostname from new schema. Still need to test locally but wanted to get early feedback. 
- small edits to resourceByHostname query
- updated tests
Waiting on SID-219 and SID-220, I will pull those changes before merging this.
> Add reads (hostname) for new schema

- pkg/storage/db.go
- pkg/storage/db_test.go
The schema management code uses postgres driver directly w/o golang sql wrapper, so it does not have reconnect logic that is present in go sql by default:
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L784
Adding PingContext should re-initialize connection if it is in bad state before any schema related queries are run.
> Workaround for using closed connections

- db-migrations/000005_adding_owners.down.sql
- db-migrations/000005_adding_owners.up.sql
We are modifying the database to satisfy the following constraints:
```
Every account has only one owner
Every account has one or more champions
Any of champions can be null (but should not)
```
**TODO:**
> Adding champions to account owners

- bulk-export/README.md
- bulk-export/export.sh
- bulk-export/export.sql
**Caveat: this is not the code I am most proud of. It solves the problem of bulk export with new schema that is a blocker right now, and which we can not implement properly due to conflicting priorities. The expectation is for "proper" bulk export API with new schema to be implemented later.**
The script talks directly to the Postgres DB (ideally - replica). All JSON serialization is done on Postgres side. Some local wrangling with `jq` to combine results.
Output is designed to be 100% compatible with output of API endpoint described in api.yaml, so any existing code to parse the data can be re-used.
I was able to run this with staging DB instance that has large amount of data, and it produces valid JSON that has the number of entries matching the count of active resources for point in …
> Stopgap script to unblock work depending on resources export for point in time

- pkg/storage/db.go
To encourage DRY, I have removed the repetitive string concatenation and instead am using the more common backticks ` for multi-line strings
> Removed string concatenation to improve uniformity

- Dockerfile
We have to use numeric `uid` and `gid` as the container does not have `/etc/passwd` file, so docker "refuses" to use string names during build.
0 is uid/gid  used for root.
> Fix docker permissions

- db-migrations/000006_no_dual_writes.down.sql
- db-migrations/000006_no_dual_writes.up.sql
- pkg/storage/db.go
- pkg/storage/schema.go
- tests/storage_test.go
As our confidence in new schema is rising, this is the beginning of work to get rid of the old schema:
* Disable dual-writes via schema version
* Clean-up integration tests code
Reason the old schema drop is not in the same PR - we would like to have writes to tables we plan to drop to stop before we try to drop them to avoid errors in production, which will require the drop logic to be a separate migration.
This also gives us a chance to recover any missed events in old schema from new or by replaying events if we discover issues.
> Start removing dual-writes

- bulk-export/export.sql
This allows the resulting bulk-export json to reflect a CloudAssetDetail struct 
```type CloudAssetDetails struct {
PrivateIPAddresses []string          `json:"privateIpAddresses"`
PublicIPAddresses  []string          `json:"publicIpAddresses"`
Hostnames          []string          `json:"hostnames"`
ResourceType       string            `json:"resourceType"`
AccountID          string            `json:"accountId"`
Region             string            `json:"region"`
ARN                string            `json:"arn"`
Tags               map[string]string `json:"tags"`
}```
> changed metadata to tags for json consistency

- Makefile
- README.md
- docker-compose.yaml
- tests/test-data/data.sql
- tests/test-data/schema.sql
First PR for [SID-442](https://asecurityteam.atlassian.net/browse/SID-442). This PR addresses need to pre-populate local instance of postgres with test data to help with API development. In this PR there are **SQL** scripts to load schema and data while postgres container is spun up.
Ran
- docker-compose down -v
- docker-compose up -d
- Verified by connecting to postgres, tables are populated with test data
> Adding scripts to populate local postgres instance with test data

- pkg/storage/db.go
- pkg/storage/db_test.go
The code before this change used to return JSON with all fields but ARN ID empty for cases when non-existent ARN was passed. Fixed to return 404 instead.
> Fix invalid result for empty lookup

- api.yaml
- main.go
- pkg/domain/storage_schema.go
- pkg/handlers/v1/force_schema.go
- pkg/handlers/v1/get_schema_version.go
- pkg/handlers/v1/get_schema_version_test.go
- pkg/handlers/v1/mock_storage_test.go
- pkg/storage/schema.go
- pkg/storage/schema_test.go
- tests/storage_test.go
Introduce additional field in response for GET version that tells if the database schema is in "dirty" state after a failed migration.
> Report the state of database schema for GET version

- api.yaml
- pkg/handlers/v1/schema_version_down.go
- pkg/handlers/v1/schema_version_up.go
- pkg/logs/migration_success.go
* Add logging on success to schema up/down migrations so that the operator can monitor long running migrations.
* Add asynchronous endpoints for use with long-running migrations (the http->lambda middleware calls lambda and returns immediately).
> Async schema migrations and additional logging.

- pkg/domain/storage_schema.go
- pkg/storage/mock_storage_migrator_test.go
- pkg/storage/schema.go
- pkg/storage/schema_test.go
Force reconnect/re-init the migrator on migration errors.
Manual testing shows this fixes the bug where failed migration renders the DB connection unusable for any subsequent migrations until the process is restarted.
> Fix the issue with failed migrations "poisoning" the db connection for susequent migrations

- db-migrations/000007_publicip_resourceid_index.down.sql
- db-migrations/000008_privateip_resourceid_index.down.sql
- db-migrations/000008_privateip_resourceid_index.up.sql
Using the same index name with different tables does not seem to work with PSQL, so the migration #8 was essentially no-op, as the index already existed. Giving index in #8  a unique name solves this (tested locally).
> Fix overlapping index names in schema migration

- api.yaml
- db-migrations/000012_adding_indexes_on_aws_resource_relationship.down.sql
- db-migrations/000012_adding_indexes_on_aws_resource_relationship.up.sql
- pkg/domain/cloud.go
- pkg/handlers/v1/cloud_insert.go
- pkg/handlers/v1/cloud_insert_test.go
- pkg/storage/db.go
- pkg/storage/db_test.go
Please refer [SID-511](https://asecurityteam.atlassian.net/browse/SID-511)
Also, creating indexes on aws_resource_relationship table as per existing system we only maintain one entry for ADDED resource until we see a DELETED event. Without index we will have multiple entries which is not ideal.
* Unit teting
* Ran migrations on local
* Manual end to end tests via POST /v1/cloud/change
> Adding ability to handle ENI relationships

- db-migrations/000013_updating_joins.down.sql
- db-migrations/000013_updating_joins.up.sql
- integration/tests/client_test.go
- pkg/domain/cloud.go
- pkg/handlers/v1/cloud_fetch_test.go
- pkg/handlers/v1/insert_account_owner.go
- pkg/storage/db.go
- pkg/storage/db_test.go
Replaced inner joins with left joins so we do not return an empty set when there are no account owners. This was tested with schema version 12 and 13 with and without an account owner, and with and without champions. Both versions work with no champions, only 13 works with no account owner. Also needed to make some strings nullable because of the null fields that are now returned when there is no account owner. Did a little research, and it seems pointers are the easiest way to work with null strings returned by the sql library we are using.
This is my first time doing a migration, so let me know if this is incorrect!
> Replace inner joins with left joins on resource to champion

- .travis.yml
- Makefile
- integration/tests/client_test.go
Added testing against master as the last step of the CI. This will only run if there are changes either to the API (api.yaml) or to the tests in the current branch.
> SID-630 Add Integration Testing Against Master to CI

- db-migrations/000012_adding_indexes_on_aws_resource_relationship.down.sql
* On schema down we see following error 
`ERROR:  DROP INDEX CONCURRENTLY cannot run inside a transaction block`
* This hot fix is to address the issue
> Hotfix as Index can not be dropped concurrently in transaction

- api.yaml
Added a separate object schema to validate input of owners and champions (there is a ticket to re-combine when we are ready).
I would love any input on whether this is too strict, or even too loose. 
This has been tested locally, we have a ticket to address integration testing on this endpoint.
I will need to followup with updating api.yaml on BB as well.
> Add validation for aws account input

- .travis.yml
- integration/tests/cloudchanges_test.go
- integration/tests/lookup_by_resourceid_test.go
- integration/tests/sample_data_test.go
Some interesting workarounds for things that openapi generated code prevents from breaking :) (which confirms openapi generation is great)
> Integration tests for lookup by resource ID endpoint

- api.yaml
RR should not be included in the object that we return for GET requests.
> Removing related resources from GET endpoint

- integration/tests/lookup_by_hostname_test.go
- integration/tests/main_test.go
* Adding integration tests for `/v1/cloud/hostname` API
* Most of the implementation is similar to `/v1/cloud/resourceid/` API tests, hence performed some refactoring to reuse code
> Adding integration test for hostname and some refactoring

- .travis.yml
- integration/tests/sample_data_test.go
https://github.com/asecurityteam/asset-inventory-api/blob/master/integration/tests/cloudchanges_test.go#L107 is where resource type is owerwritten due to lack of validation (in a race-condition-prone fashion :(). 
We can not rely on proper resource type to be present in response for other tests.
This should unbreak master branch. Follow-up PR to re-enable master run coming next.
> Account for resource type being overwritten by broken test

- pkg/storage/db.go
- pkg/storage/db_test.go
Ensuring that when an error happens for a cloud change POST we return an error right away so that the transaction isn't hanging around with an error causing subsequent queries to fail. This does mean that if any sql query fails on a request the whole request fails. 
Note: This was not and will not be poisoning following requests. The problem was with queries in the same transaction. When one query fails and breaks the transaction, the following queries in the transaction cannot run properly and we get a bunch of error logs. Not dire, but not ideal either.
I tried to find a way to write an integration test to make sure this fails gracefully, but luckily I couldn't find a way to replicate this problem with all of our new validations.
(Also lint doesn't like "cancelled" as a spelling)
> Fix transaction getting poisoned

- .travis.yml
- integration/tests/main_test.go
- integration/tests/schema_helpers_test.go
- pkg/storage/schema.go
The goal of this pull request is to update the min schema version to something closer to current than 6(which is way behind).
The integration tests broke in `master-integration` but will likely not work until I merge in this change and add them back to the travis builds.
> minimum schema version updated

- .travis.yml
- codecov.yml
I am adding back the integration tests for master.
I am also commenting out codecov temporarily as we can only make updates to the codecov file in the master branch and I can't merge to master until we get it passing. My plan is to fast follow this PR and re-enable codecov
> adding master integration testing back

- integration/tests/cloudchanges_test.go
- pkg/storage/db.go
- pkg/storage/db_test.go
Two things this PR doesn't change:
1. Relationship arnid use
2. Returning multiple assets for the resource id lookup
About #2: We hadn't fully discussed whether we want to be able to return multiple assets for a resource id lookup. If we want this I can add to another PR. Something to note -- when I make this change locally we return over 3000 records for our "Valid" test because we use the same timestamps for many entries and multiple owner/champion combos. I assume this wouldn't be the case in real life, but if this is a concern I can also address this in another ticket.
> Allow multiple arn id, as long as the region and/or owners are different.

- api.yaml
- integration/tests/sample_data_test.go
Schema is changed to set maximum number of hostname in array to 1. If more than one hostnames is sent, request will fail and an error message will be returned. 
{"changes":[{"privateIpAddresses":["10.0.0.1","10.0.0.2"],"publicIpAddresses":["8.8.8.8","8.8.4.4"],"hostnames":["myhostname.us-west-1.amazonaws.com","anotherhostname.com"],"changeType":"DELETED"}],"changeTime":"2018-01-13T22:51:48.324359102Z","resourceType":"AWS:EC2:Instance","accountId":"012345678901","region":"us-west-1","arn":"arn:aws:ec2:us-west-1:012345678901:instance/i-0123456789abcdef0","tags":{"Name":"ValidInstance","resource_owner":"jsmith"}}
test_1      |
test_1      | 2020/09/15 21:05:41
test_1      | HTTP/1.1 400 Bad Request
test_1      | Content-Length: 378
test_1      | Content-Type: application/json
test_1      | …
> Add limit to number of hostname sent
